### ISSUE TITLE
Unable to run the test scripts

### ISSUE THREAD

**Issue by Shashankti** [zavolanlab/RCRUNCH#17]
Hello Maria Katsantoni,

I intend to use the RCRUNCH pipeline for some eCLIP data and I was able to install the pipeline with all the required dependencies, however I have been unable to run the test scripts for both local and on hpc via slurm. Earlier I faced issue with some input options being incompatible with our hpc i.e. `qos`  and `tmp`. Even after adjusting for these parameters the test script fails to run and a log output is not generated (or I am unable to find the logs), therefore I have not been able to troubleshoot the issue. I am attaching the output file from the submitted job, I hope this is sufficient. Please let me know if you need any more information. 

Thank you for your time,
Shashank
[test_slurm_output.txt](https://github.com/zavolanlab/RCRUNCH/files/10535946/test_slurm_output.txt)

**Comment by mkatsanto** [comment]
Hi @Shashankti thanks for looking at RCRUNCH. Have you tried to execute the local version of the test? Does this work? This would help with pinpointing if this is indeed a cluster incompatibility. Another point is that even when executing this for the slurm the bash script (bash test/test_singularity_execution/test_slurm.sh )should be executed locally, which I am not sure is the case here. Additionally, you could comment the following line: https://github.com/zavolanlab/RCRUNCH/blob/d638d2ce4e7562dcce25aa770a12fcd072b684c1/test/test_singularity_execution/test_slurm.sh#L9 
so that the log files are retained and we can take a look.

**Comment by Shashankti** [comment]
Hello again, thank you for your quick reply. I was able to save the log files thanks to your suggestions. I had earlier ran the test_slurm script locally however since I was not able to save the output, I decided to run it via sbatch for easier sharing of logs. Nevertheless I ran both `test_local` and `test_slurm` scripts again.

I believe the issue is with the step `umi_tools_format`. I get the following error:
`python: can't open file '/home/mpg02/MDMP/shashank.tiwari/RCRUNCH/workflow/scripts/mk_convert_fastq_to_umi_format.py': [Errno 2] No such file or directory`
which I thought could have been an issue of permissions, however all the files have read, write and execute  permissions so I am not sure what is the cause of this error. I am attaching the output log files here. Please let me know if you need any other information.

Once again thank you for your help.
[sample=ENCFF616FCF_ENCFF495ZPY-14678786-amp035.txt](https://github.com/zavolanlab/RCRUNCH/files/10537221/sample.ENCFF616FCF_ENCFF495ZPY-14678786-amp035.txt)
[umi_format__ENCFF616FCF_ENCFF495ZPY.stderr.txt](https://github.com/zavolanlab/RCRUNCH/files/10537228/umi_format__ENCFF616FCF_ENCFF495ZPY.stderr.txt)
[test_local.log](https://github.com/zavolanlab/RCRUNCH/files/10537233/test_local.log)
[test_slurm.log](https://github.com/zavolanlab/RCRUNCH/files/10537234/test_slurm.log)

**Comment by mkatsanto** [comment]
Hi @Shashankti this is indeed weird behaviour.. and just to make sure do you execute
 bash test/test_singularity_execution/test_local.sh from the home directory path as advised? 
Because there are some binding of paths happening due to singularity and currently you have to be in the home directory (RCRUNCH) when you execute the test or the workflow

**Comment by Shashankti** [comment]
Yes, I execute the files from the RCRUNCH home directory. Also, when running the `test_slurm` script, the first two steps, generating the star index and cutadapt seem to be working fine, so I am not really sure what is the issue in this step. I will try to make a fresh install on a different machine and try to see if I can replicate the issue locally as well.

**Comment by mkatsanto** [comment]
> I decided to run it via sbatch for easier sharing of logs

I just saw this comment. The thing is we already do sbatch within the workflow, so by calling sbatch on the slurm test the workflow would try to do sbatch when it is already running in the cluster. The idea is that the execution of the script is done locally and the rules called within are sent to the cluster if you execute the slurm script, or not if you do the local one.

**Comment by Shashankti** [comment]
Sorry for the confusion, I am not running the test via sbatch, I only did that in the first attempt when I was unable to save the logs, thats why I had used a job script to save the output in a file. For all the other attempts, I ran the script directly via terminal

**Comment by mkatsanto** [comment]
Hi @Shashankti did the new test run work? You can send the logs and also the results (by commenting line https://github.com/zavolanlab/RCRUNCH/blob/d638d2ce4e7562dcce25aa770a12fcd072b684c1/test/test_singularity_execution/test_slurm.sh#L10)
It would also help to know which version of singularity you use. 
I tried myself to run the test locally but haven't managed to reproduce the error you are getting so any more info is highly appreciated.

**Comment by Shashankti** [comment]
Hey @mkatsanto , the files which I shared in the second comment are from running the scripts directly via the terminal and not via sbatch, again sorry for the confusion.
I am using singularity version 3.8.5. Unfortunately I could not find the time to reinstall on a different machine. I will let you know if I am able to reproduce the errors. 

> Hello again, thank you for your quick reply. I was able to save the log files thanks to your suggestions. I had earlier ran the test_slurm script locally however since I was not able to save the output, I decided to run it via sbatch for easier sharing of logs. Nevertheless I ran both `test_local` and `test_slurm` scripts again.
> 
> I believe the issue is with the step `umi_tools_format`. I get the following error: `python: can't open file '/home/mpg02/MDMP/shashank.tiwari/RCRUNCH/workflow/scripts/mk_convert_fastq_to_umi_format.py': [Errno 2] No such file or directory` which I thought could have been an issue of permissions, however all the files have read, write and execute permissions so I am not sure what is the cause of this error. I am attaching the output log files here. Please let me know if you need any other information.
> 
> Once again thank you for your help. [sample=ENCFF616FCF_ENCFF495ZPY-14678786-amp035.txt](https://github.com/zavolanlab/RCRUNCH/files/10537221/sample.ENCFF616FCF_ENCFF495ZPY-14678786-amp035.txt) [umi_format__ENCFF616FCF_ENCFF495ZPY.stderr.txt](https://github.com/zavolanlab/RCRUNCH/files/10537228/umi_format__ENCFF616FCF_ENCFF495ZPY.stderr.txt) [test_local.log](https://github.com/zavolanlab/RCRUNCH/files/10537233/test_local.log) [test_slurm.log](https://github.com/zavolanlab/RCRUNCH/files/10537234/test_slurm.log)

**Comment by Shashankti** [comment]
Hello again @mkatsanto , I installed RCRUNCH again on a local machine and ran the test scripts, initially I got the following error:
```
input files already exist, 3/3
Traceback (most recent call last):
  File "/opt/user_software/miniconda3_envs/rcrunch/lib/python3.10/site-packages/snakemake/__init__.py", line 605, in snakemake
    workflow.include(
  File "/opt/user_software/miniconda3_envs/rcrunch/lib/python3.10/site-packages/snakemake/workflow.py", line 1186, in include
    snakefile = infer_source_file(snakefile, basedir)
  File "/opt/user_software/miniconda3_envs/rcrunch/lib/python3.10/site-packages/snakemake/sourcecache.py", line 269, in infer_source_file
    if is_local_file(path_or_uri):
  File "/opt/user_software/miniconda3_envs/rcrunch/lib/python3.10/site-packages/snakemake/common/__init__.py", line 84, in is_local_file
    return parse_uri(path_or_uri).scheme == "file"
  File "/opt/user_software/miniconda3_envs/rcrunch/lib/python3.10/site-packages/snakemake/common/__init__.py", line 88, in parse_uri
    from smart_open import parse_uri
  File "/opt/user_software/miniconda3_envs/rcrunch/lib/python3.10/site-packages/smart_open/__init__.py", line 34, in <module>
    from .smart_open_lib import open, parse_uri, smart_open, register_compressor  # noqa: E402
  File "/opt/user_software/miniconda3_envs/rcrunch/lib/python3.10/site-packages/smart_open/smart_open_lib.py", line 35, in <module>
    from smart_open import doctools
  File "/opt/user_software/miniconda3_envs/rcrunch/lib/python3.10/site-packages/smart_open/doctools.py", line 21, in <module>
    from . import transport
  File "/opt/user_software/miniconda3_envs/rcrunch/lib/python3.10/site-packages/smart_open/transport.py", line 104, in <module>
    register_transport("smart_open.s3")
  File "/opt/user_software/miniconda3_envs/rcrunch/lib/python3.10/site-packages/smart_open/transport.py", line 49, in register_transport
    submodule = importlib.import_module(submodule)
  File "/opt/user_software/miniconda3_envs/rcrunch/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/user_software/miniconda3_envs/rcrunch/lib/python3.10/site-packages/smart_open/s3.py", line 17, in <module>
    import boto3
  File "/opt/user_software/miniconda3_envs/rcrunch/lib/python3.10/site-packages/boto3/__init__.py", line 17, in <module>
    from boto3.session import Session
  File "/opt/user_software/miniconda3_envs/rcrunch/lib/python3.10/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/opt/user_software/miniconda3_envs/rcrunch/lib/python3.10/site-packages/botocore/session.py", line 26, in <module>
    import botocore.client
  File "/opt/user_software/miniconda3_envs/rcrunch/lib/python3.10/site-packages/botocore/client.py", line 15, in <module>
    from botocore import waiter, xform_name
  File "/opt/user_software/miniconda3_envs/rcrunch/lib/python3.10/site-packages/botocore/waiter.py", line 18, in <module>
    from botocore.docs.docstring import WaiterDocstring
  File "/opt/user_software/miniconda3_envs/rcrunch/lib/python3.10/site-packages/botocore/docs/__init__.py", line 15, in <module>
    from botocore.docs.service import ServiceDocumenter
  File "/opt/user_software/miniconda3_envs/rcrunch/lib/python3.10/site-packages/botocore/docs/service.py", line 14, in <module>
    from botocore.docs.client import ClientDocumenter, ClientExceptionsDocumenter
  File "/opt/user_software/miniconda3_envs/rcrunch/lib/python3.10/site-packages/botocore/docs/client.py", line 14, in <module>
    from botocore.docs.example import ResponseExampleDocumenter
  File "/opt/user_software/miniconda3_envs/rcrunch/lib/python3.10/site-packages/botocore/docs/example.py", line 13, in <module>
    from botocore.docs.shape import ShapeDocumenter
  File "/opt/user_software/miniconda3_envs/rcrunch/lib/python3.10/site-packages/botocore/docs/shape.py", line 19, in <module>
    from botocore.utils import is_json_value_header
  File "/opt/user_software/miniconda3_envs/rcrunch/lib/python3.10/site-packages/botocore/utils.py", line 37, in <module>
    import botocore.httpsession
  File "/opt/user_software/miniconda3_envs/rcrunch/lib/python3.10/site-packages/botocore/httpsession.py", line 46, in <module>
    from urllib3.contrib.pyopenssl import (
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 50, in <module>
    import OpenSSL.SSL
  File "/opt/user_software/miniconda3_envs/rcrunch/lib/python3.10/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import SSL, crypto
  File "/opt/user_software/miniconda3_envs/rcrunch/lib/python3.10/site-packages/OpenSSL/SSL.py", line 19, in <module>
    from OpenSSL.crypto import (
  File "/opt/user_software/miniconda3_envs/rcrunch/lib/python3.10/site-packages/OpenSSL/crypto.py", line 3253, in <module>
    utils.deprecated(
TypeError: deprecated() got an unexpected keyword argument 'name'
Exit status: 1
```
which I was able to fix following [this](https://stackoverflow.com/questions/74041308/pip-throws-typeerror-deprecated-error). After this I was able to run the test script locally without any issues. I still do not understand the reason why I am facing issues on the hpc. The only difference on the hpc is that I had to build `micromamba`, as I can not install any package in the base environment due to lack of permissions. Would you suggest that I create a new environment on the hpc without using `mamba`?

**Comment by mkatsanto** [comment]
Hi @Shashankti glad to know that it worked for you locally. Regarding the hpc system, I think you can do :
```
conda env create -f install/environment.yml
```
It just takes more time, this is why I was suggesting the mamba installation in the base env. I hope this helps!

**Comment by Shashankti** [comment]
Hey @mkatsanto , thanks for your help. The issue was indeed due to micromamba installation
